import React, { useEffect, useRef, useState } from 'react';
import { motion } from 'motion/react';
import type { AppScreen } from '../../types';
import { api, isLoggedIn } from '../../services/backend';

interface Props { onNavigate:(screen:AppScreen)=>void; onShowToast:(message:string,icon?:string)=>void }
type Status = {collaborator:any;listings:any[]};
const input='w-full rounded-xl border border-[#d8d2bc] bg-[#f8f5eb] px-4 py-3 text-sm text-[#343723] outline-none focus:border-[#898861] focus:ring-2 focus:ring-[#898861]/15';

export const CollaboratorScreen:React.FC<Props>=({onNavigate,onShowToast})=>{
  const [status,setStatus]=useState<Status|null>(null);const [wrongRole,setWrongRole]=useState(false);
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
  const [name,setName]=useState(''); const [town,setTown]=useState(''); const [kind,setKind]=useState<'visit'|'eat'>('visit');
  const [category,setCategory]=useState(''); const [description,setDescription]=useState(''); const [cost,setCost]=useState(''); const [photo,setPhoto]=useState<File|null>(null);
  const [govId,setGovId]=useState<File|null>(null); const [uploadingId,setUploadingId]=useState(false); const [uploadingPhoto,setUploadingPhoto]=useState(false);
  const idInput=useRef<HTMLInputElement>(null); const photoInput=useRef<HTMLInputElement>(null);
  const refresh=()=>api.me().then(me=>{if(me.role!=='collaborator')throw new Error('This area is for collaborator accounts. Create or sign in to a host account to continue.');return api.collaboratorStatus()}).then(setStatus).catch(e=>{setWrongRole(true);onShowToast(e instanceof Error?e.message:'Could not load collaborator data.','error')}).finally(()=>setLoading(false));
  useEffect(()=>{if(isLoggedIn())void refresh();else setLoading(false)},[]);
  const uploadId=async()=>{if(!govId)return;setUploadingId(true);try{await api.uploadDocument('govt_id',govId);setGovId(null);await refresh();onShowToast('Government ID received for review.','check_circle')}catch(e){onShowToast(e instanceof Error?e.message:'Upload failed.','error')}finally{setUploadingId(false)}};
  const uploadEvidence=async(file:File)=>{
    setUploadingPhoto(true);
    try{const coords=await new Promise<GeolocationCoordinates>((resolve,reject)=>{if(!navigator.geolocation){reject(new Error('Location is unavailable in this browser.'));return;}navigator.geolocation.getCurrentPosition(pos=>resolve(pos.coords),()=>reject(new Error('Allow location access to attach a location to this photo.')), {enableHighAccuracy:true,timeout:15000});});
      await api.uploadDocument('geotagged_photo',file,coords.latitude,coords.longitude);await refresh();onShowToast('Location-stamped photo received.','check_circle');
    }catch(e){onShowToast(e instanceof Error?e.message:'Photo upload failed.','error')}finally{setUploadingPhoto(false)}
  };
  const submit=async()=>{
    if(!name.trim()||!town.trim()||!category.trim()||!description.trim()||!photo){onShowToast('Add the place details and one original place photo.','info');return}
    setSaving(true);
    try{const result=await api.createListing({name:name.trim(),kind,town:town.trim(),category:category.trim(),description:description.trim(),cost_inr:cost?Number(cost):undefined});
      await api.uploadListingPhoto(result.listing_id,photo);await refresh();setName('');setTown('');setCategory('');setDescription('');setCost('');setPhoto(null);
      onShowToast(result.decision==='hidden_gem'?'Model approved this place; photo uploaded and publication status updated.':'Sent to the admin review queue with the model’s evidence.','check_circle');
    }catch(e){onShowToast(e instanceof Error?e.message:'Could not submit this place.','error')}finally{setSaving(false)}
  };
  if(!isLoggedIn())return <main className="mx-auto max-w-4xl px-6 py-20"><p className="text-xs uppercase tracking-[.2em] text-[#7d2826]">SideQuest / Local hosts</p><h1 className="mt-3 font-headline text-4xl text-[#343723]">Share a place worth finding.</h1><p className="mt-4 max-w-xl leading-7 text-[#595a4a]">Sign in with a collaborator account to submit a place, share proof and track its review.</p><button onClick={()=>onNavigate('login')} className="mt-7 rounded-xl bg-[#343723] px-6 py-3 text-sm font-semibold text-[#f8f5eb]">Sign in</button></main>;
  if(wrongRole)return <main className="mx-auto max-w-4xl px-6 py-20"><p className="text-xs uppercase tracking-[.2em] text-[#7d2826]">SideQuest / Local hosts</p><h1 className="mt-3 font-headline text-4xl text-[#343723]">A separate host workspace.</h1><p className="mt-4 max-w-xl leading-7 text-[#595a4a]">Your current account is a traveller account. Create a collaborator account to submit a place and upload verification evidence.</p><button onClick={()=>onNavigate('register')} className="mt-7 rounded-xl bg-[#343723] px-6 py-3 text-sm font-semibold text-[#f8f5eb]">Create a host account</button></main>;
  if(loading)return <div className="mx-auto max-w-6xl px-6 py-20 text-[#595a4a]">Loading your host workspace…</div>;
  return <main className="mx-auto w-full max-w-7xl px-5 pb-16 pt-8 md:px-10">
    <motion.header initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="mb-9 grid gap-5 border-b border-[#d8d2bc] pb-7 md:grid-cols-[1fr_auto] md:items-end"><div><p className="text-xs uppercase tracking-[.2em] text-[#7d2826]">SideQuest / Local hosts</p><h1 className="mt-2 font-headline text-4xl text-[#343723] md:text-6xl">Places deserve<br/>a good introduction.</h1><p className="mt-4 max-w-2xl text-base leading-7 text-[#595a4a]">Submit a place with evidence. SideQuest’s model reviews it; uncertain cases go to the team for a human decision.</p></div><div className="rounded-2xl border border-[#d8d2bc] bg-[#f8f5eb] px-5 py-4"><p className="text-xs uppercase tracking-wider text-[#898861]">Host review</p><p className="mt-1 text-lg font-semibold capitalize text-[#343723]">{status?.collaborator?.verification_status||'Not started'}</p></div></motion.header>
    <div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_minmax(320px,.82fr)]">
      <section className="space-y-6">
        <div className="rounded-2xl border border-[#d8d2bc] bg-[#f8f5eb] p-5 md:p-7"><div className="flex items-start justify-between gap-5"><div><p className="text-xs uppercase tracking-[.16em] text-[#898861]">01 / Identity</p><h2 className="mt-1 font-headline text-2xl text-[#343723]">Government ID</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[#595a4a]">A private document for host verification. Only admins can review it.</p></div><span className="material-symbols-outlined text-3xl text-[#7d2826]">badge</span></div><input ref={idInput} type="file" accept="application/pdf,image/jpeg,image/png" className="sr-only" onChange={e=>setGovId(e.target.files?.[0]||null)}/><div className="mt-5 flex flex-wrap items-center gap-3"><button onClick={()=>idInput.current?.click()} className="rounded-xl border border-[#aaa78c] px-4 py-2.5 text-sm font-semibold text-[#343723] hover:bg-[#eeeadb]">Choose ID file</button><span className="text-sm text-[#595a4a]">{govId?.name|| (status?.collaborator?.document_type==='govt_id'?'ID submitted for review':'PDF, JPG or PNG · max 8 MB')}</span>{govId&&<button disabled={uploadingId} onClick={()=>void uploadId()} className="rounded-xl bg-[#343723] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{uploadingId?'Uploading…':'Upload securely'}</button>}</div></div>
        <div className="rounded-2xl border border-[#d8d2bc] bg-[#f8f5eb] p-5 md:p-7"><p className="text-xs uppercase tracking-[.16em] text-[#898861]">02 / A place to discover</p><h2 className="mt-1 font-headline text-2xl text-[#343723]">Tell us about your place</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="space-y-2 text-sm font-medium text-[#595a4a] sm:col-span-2">Place or business name<input className={input} value={name} onChange={e=>setName(e.target.value)} placeholder="The name visitors know"/></label><label className="space-y-2 text-sm font-medium text-[#595a4a]">Town or city<input className={input} value={town} onChange={e=>setTown(e.target.value)} placeholder="Town in India"/></label><label className="space-y-2 text-sm font-medium text-[#595a4a]">Place type<select className={input} value={kind} onChange={e=>setKind(e.target.value as any)}><option value="visit">Place to visit</option><option value="eat">Food & drink</option></select></label><label className="space-y-2 text-sm font-medium text-[#595a4a]">Category<input className={input} value={category} onChange={e=>setCategory(e.target.value)} placeholder="Waterfall, cafe, craft…"/></label><label className="space-y-2 text-sm font-medium text-[#595a4a]">Typical cost per person (₹)<input className={input} type="number" min="0" value={cost} onChange={e=>setCost(e.target.value)} placeholder="Optional"/></label><label className="space-y-2 text-sm font-medium text-[#595a4a] sm:col-span-2">What should a traveller know?<textarea className={`${input} min-h-28 resize-y`} maxLength={1500} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe how to find it, what makes it worth a visit and any access notes."/></label></div>
          <div className="mt-5 rounded-xl border border-dashed border-[#aaa78c] p-4"><input ref={photoInput} type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={e=>setPhoto(e.target.files?.[0]||null)}/><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="font-semibold text-[#343723]">Original place photo</p><p className="mt-1 text-xs text-[#6e6e5c]">Use a real image of your place. No stock or generated images.</p></div><button type="button" onClick={()=>photoInput.current?.click()} className="rounded-lg border border-[#aaa78c] px-4 py-2 text-sm font-semibold text-[#343723]">{photo?.name||'Choose photo'}</button></div></div>
          <button type="button" disabled={saving} onClick={()=>void submit()} className="mt-5 min-h-12 w-full rounded-xl bg-[#7d2826] px-5 text-sm font-semibold text-white transition hover:bg-[#67211f] disabled:opacity-50">{saving?'Reviewing and saving…':'Submit place for review'}</button><p className="mt-3 text-xs leading-5 text-[#6e6e5c]">Model-approved gems are published after host verification and photo upload. Places the model cannot verify are sent to an admin; submission does not guarantee acceptance.</p>
        </div>
        <div className="rounded-2xl border border-[#d8d2bc] bg-[#f8f5eb] p-5 md:p-7"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.16em] text-[#898861]">03 / Evidence</p><h2 className="mt-1 font-headline text-2xl text-[#343723]">Location-stamped photos</h2></div><span className="material-symbols-outlined text-3xl text-[#7d2826]">photo_camera</span></div><p className="mt-2 text-sm leading-6 text-[#595a4a]">Capture your current location and attach it to a real photo of the place. Your coordinates are visible to reviewers.</p><input type="file" accept="image/jpeg,image/png,image/webp" multiple className="mt-5 block w-full text-sm text-[#595a4a] file:mr-3 file:rounded-lg file:border-0 file:bg-[#343723] file:px-4 file:py-2.5 file:font-semibold file:text-white" onChange={e=>{const files=Array.from(e.target.files||[]);void Promise.all(files.map(uploadEvidence));e.currentTarget.value=''}}/><p className="mt-3 text-xs text-[#898861]">{uploadingPhoto?'Attaching location and uploading…':`${status?.documents?.filter((d:any)=>d.doc_type==='geotagged_photo').length||0} evidence photos received`}</p></div>
      </section>
      <aside><section className="rounded-2xl bg-[#343723] p-6 text-[#f3efdf] md:p-7"><p className="text-xs uppercase tracking-[.16em] text-[#c6c49f]">Your listing record</p><h2 className="mt-2 font-headline text-3xl">Measured over time.</h2><p className="mt-3 text-sm leading-6 text-[#e1deca]">We show only view and rating counts recorded by SideQuest. New listings start with no activity.</p><div className="mt-6 space-y-4 border-t border-white/20 pt-5">{(status?.listings||[]).length===0?<p className="text-sm text-[#c6c49f]">No submissions yet.</p>:(status?.listings||[]).map((item:any)=><article key={item.id} className="border-b border-white/15 pb-4 last:border-0"><div className="flex justify-between gap-3"><h3 className="font-semibold">{item.name}</h3><span className="text-xs capitalize text-[#d9a69b]">{String(item.review_status||item.decision).replace(/_/g,' ')}</span></div><p className="mt-1 text-xs text-[#c6c49f]">{item.city} · {item.kind}</p><div className="mt-3 flex gap-5 text-xs text-[#e1deca]"><span>{item.view_count||0} views</span><span>{item.average_rating?`${item.average_rating} / 5 · ${item.rating_count} ratings`:'No ratings yet'}</span></div><p className="mt-2 text-xs leading-5 text-[#c6c49f]">{item.evaluation?.reason||'Model review complete.'}</p></article>)}</div></section><section className="mt-5 rounded-2xl border border-[#d8d2bc] p-6"><p className="text-xs uppercase tracking-[.16em] text-[#898861]">Review process</p><ol className="mt-4 space-y-4 text-sm leading-6 text-[#595a4a]"><li><b className="mr-2 text-[#7d2826]">1</b>Model evaluates existing evidence and safety context.</li><li><b className="mr-2 text-[#7d2826]">2</b>Insufficient evidence goes to a human admin review.</li><li><b className="mr-2 text-[#7d2826]">3</b>Approved places can appear in discovery after host verification.</li></ol><button onClick={()=>onNavigate('terms')} className="mt-5 text-sm font-semibold text-[#7d2826] underline underline-offset-4">Read host and platform terms</button></section></aside>
    </div>
  </main>
};
